/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AchievementList: typeof import('./components/rewards/AchievementList.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    CourseProgress: typeof import('./components/course/CourseProgress.vue')['default']
    DynamicBackground: typeof import('./components/DynamicBackground.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ErrorMessage: typeof import('./components/common/ErrorMessage.vue')['default']
    Forbidden: typeof import('./components/common/Forbidden.vue')['default']
    GlobalLoading: typeof import('./components/common/GlobalLoading.vue')['default']
    LessonProgress: typeof import('./components/lesson/LessonProgress.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    NoteEditor: typeof import('./components/lesson/NoteEditor.vue')['default']
    NotFound: typeof import('./components/common/NotFound.vue')['default']
    QuizPlayer: typeof import('./components/lesson/QuizPlayer.vue')['default']
    RadarChart: typeof import('./components/charts/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLevel: typeof import('./components/rewards/UserLevel.vue')['default']
    VideoPlayer: typeof import('./components/lesson/VideoPlayer.vue')['default']
  }
}
